apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-odqz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-odqz
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-odqz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-odqz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-odqz
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pqld-tenant/rhtap-demo-app/hacbs-test-project-odqz@sha256:f0cdf929564b4add152345cf692274fd8bd8e5e20fb3b4bf854b9496b9149637
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
